all:
	g++ -O8 -I/usr/include/eigen3 -I/usr/include/python3.6 SIA_CODES/flow.cpp SIA_CODES/avalanche_module.cpp SIA_CODES/read_write.cpp SIA_CODES/calc_matrices.cpp -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6 -std=c++11  -o tune
